### ISSUE TITLE
Trying to push a project with dependencies fails

### ISSUE THREAD

**Issue by burgalon** [rnplay/rnplay-web#7]
I'm trying to push updates to my add and push seems to fail and it's hard to debug.

**Comment by jsierles** [comment]
Can you give more details on how this fails? Also, the app URL on rnplay. Thanks!

**Comment by burgalon** [comment]
https://rnplay.org/apps/DZeqjQ
The push actually succeeds, but the files do not update

**Comment by jsierles** [comment]
The files are updated to the latest commit: a1e42568b48abbf4cdea9d4a758378dd0405a41e

What might be confusing you is that we filter non-js/json files in the UI. So your html file is there, for example, but not visible or editable via the UI.

In reality this is an experimental feature that we're may pull put soon due to conflicts between dependencies in different projects. In its place, we'll allow uploading of complete app bundles, until we find time to stabilize the packager system.

**Comment by burgalon** [comment]
So now it seems like the app is updated just fine, and even node_modules are installed which is awesome! but it seems to be loading until timing-out and no error message. I'm not sure even what are my debugging options in this case.... (app is still https://rnplay.org/apps/DZeqjQ)

**Comment by jsierles** [comment]
You may have seen this during a packager restart - they restart now and then to keep things speedy.

I now see an error loading the util module. We've seen this sort of problem when projects have conflicting   modules.

So in this case I recommend holding off until we enable uploading of full app bundles. This should be within a few days. Thanks for your support!

**Comment by jsierles** [comment]
Closing this issue to open more specific ones.
